DROP TABLE IF EXISTS shopping_list2;

CREATE TABLE shopping_list2 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task TEXT NOT NULL,
  email TEXT NOT NULL,
  priority TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

